version : '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    restart: always
    volumes:
      - ./data/jenkins/jenkins_home:/var/jenkins_home
      - ./data/jenkins/var/run/docker.sock:/var/run/docker.sock
      - ./data/jenkins/usr/local/bin/docker:/usr/local/bin/docker
