version : '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8183:80

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    restart: unless-stopped
    volumes:
      - ./data/jenkins/jenkins_home:/var/jenkins_home
      - .data/jenkins/var/run/docker.sock:/var/run/docker.sock
      - ./data/jenkins/usr/local/bin/docker:/usr/local/bin/docker

  eclipse-theia:
    restart: always
    container_name: theia
    image: theiaide/theia-java:latest
    restart: unless-stopped
    init: true
    ports:
      - 4000:3000
      - 8083:8082
    volumes:
      - ./data/theia/projects:/home/project

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - TZ=Europe/Amsterdam
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    volumes:
      - ./data/vsc/config:/config
    ports:
      - 8444:8443
      - 5500:5500
    restart: unless-stopped
